version: '3'

services:

  redis:
    image: redis
    restart: always

  django:
    build: .
    command: bash -c "
      cd /multiroom-chatbot &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/multiroom-chatbot
    links:
      - redis
    depends_on:
      - redis

  bot:
    build: .
    command: bash -c "
      cd /multiroom-chatbot &&
      python manage.py rqworker default"
    volumes:
      - .:/multiroom-chatbot
    links:
      - redis
    depends_on:
      - redis
