# Generated by Django 2.2 on 2020-08-12 01:10

from django.db import migrations
from django.contrib.auth.models import User
from chat.models import Room


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_users'),
    ]

    def insert_data(apps, schema_editor):
        user = User.objects.create_superuser('admin', 'myuser@mydomain.com', 'admin')
        user.save()
        user = User.objects.create_user('user01', 'myuser@mydomain.com', 'user01')
        user.save()
        user = User.objects.create_user('user02', 'myuser@mydomain.com', 'user02')
        user.save()
        room = Room.objects.create(name='Room 1')
        room.save()
        room = Room.objects.create(name='Room 2')
        room.save()
        room = Room.objects.create(name='Room 3')
        room.save()

    operations = [
        migrations.RunPython(insert_data),
    ]
